export TFS_IMAGE_TAG="dev"
export TFS_K8S_NAMESPACE="tfs"
export TFS_K8S_HOSTNAME="192.168.2.34"
export TFS_SKIP_BUILD="NO"

# Lite-Configuration Whitelist (Rule 11)
export TFS_COMPONENTS="context device service slice pathcomp nbi webui interdomain dlt"

# Registry
export TFS_REGISTRY_IMAGES="localhost:32000/tfs/"

# Database (CockroachDB Baseline)
export CRDB_NAMESPACE="crdb"
export CRDB_DATABASE="tfs"
export CRDB_USERNAME="root"
export CRDB_PASSWORD="root"
export CRDB_SSLMODE="disable"

# NATS
export NATS_NAMESPACE="nats"

# gRPC Service Overrides (Sovereign Gateway)
export CONTEXTSERVICE_SERVICE_HOST=$TFS_K8S_HOSTNAME
export CONTEXTSERVICE_SERVICE_PORT_GRPC=30101
export DEVICESERVICE_SERVICE_HOST=$TFS_K8S_HOSTNAME
export DEVICESERVICE_SERVICE_PORT_GRPC=30202
export SERVICESERVICE_SERVICE_HOST=$TFS_K8S_HOSTNAME
export SERVICESERVICE_SERVICE_PORT_GRPC=30303
export SLICESERVICE_SERVICE_HOST=$TFS_K8S_HOSTNAME
export SLICESERVICE_SERVICE_PORT_GRPC=30404
export PATHCOMPSERVICE_SERVICE_HOST=$TFS_K8S_HOSTNAME
export PATHCOMPSERVICE_SERVICE_PORT_GRPC=31002
export INTERDOMAINSERVICE_SERVICE_HOST=$TFS_K8S_HOSTNAME
export INTERDOMAINSERVICE_SERVICE_PORT_GRPC=30011

# NBI Gateway (Sovereign Reality)
export NBISERVICE_SERVICE_HOST=$TFS_K8S_HOSTNAME
export NBISERVICE_SERVICE_PORT_HTTP=30808
